### PR TITLE
did some updating to search bar

### PR DESCRIPTION
**Pull request by MattThompson15**

### CODE REVIEW

**Comment by MagicianJoshua** [comment]
Looked over the changes, the search bar has ahd some stylings

**Review by MagicianJoshua — COMMENTED** [review]
Searchbar css looks good

**Review by MagicianJoshua — APPROVED** [review]
The css searchbar looks like it has been updated nice work

**Comment by Valleyleaf** [comment]
Reviewing

**Review by Valleyleaf — APPROVED** [review]
Approved.

**Pull request merged**
